databases:
  - name: mysitedb
    plan: free
    databaseName: youta
    user: youta

services:
  - type: web
    plan: free
    name: youta
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bookproject.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4
