databases:
  - name: mysitedb
    plan: free
    databaseName: youta
    user: youta

services:
  - type: web
    plan: free
    name: youta
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn bookproject.bookproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4